"use client";
import {useEffect,useState} from "react";
import {SlidersHorizontal} from "lucide-react";
import {getDocumentTypes} from "@/lib/api";
import type {AnalyticsPipeline,DocumentType,QueryFilters} from "@/types";

export default function ComparisonFilters({value,onChange,pipelines,archived,onArchived,search,onSearch,onReset}:{value:QueryFilters;onChange:(v:QueryFilters)=>void;pipelines:AnalyticsPipeline[];archived:boolean;onArchived:(v:boolean)=>void;search:string;onSearch:(v:string)=>void;onReset:()=>void}) {
  const [types,setTypes]=useState<DocumentType[]>([]),[error,setError]=useState(false),[open,setOpen]=useState(false),[preset,setPreset]=useState("");
  useEffect(()=>{let active=true;getDocumentTypes().then(t=>{if(active)setTypes(t);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[]);
  function dates(v:string){setPreset(v);if(v==="custom"){setOpen(true);return;}if(!v){onChange({...value,date_from:undefined,date_to:undefined});return;}const end=new Date(),start=new Date(end);start.setUTCDate(start.getUTCDate()-Number(v));onChange({...value,date_from:start.toISOString().slice(0,10),date_to:end.toISOString().slice(0,10)});}
  return <><div className="comparison-filter-controls"><label className="field">Document type<select className="select" aria-label="ประเภทเอกสาร (ธุรกิจ)" value={value.document_type_id??""} onChange={e=>onChange({...value,document_type_id:e.target.value||undefined})}><option value="">ทุกประเภทเอกสาร</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}{t.active?"":" · เก็บถาวร"}</option>)}{value.document_type_id&&!types.some(t=>t.id===value.document_type_id)&&<option value={value.document_type_id}>ประเภทที่เลือก (เก็บถาวร)</option>}</select>{error&&<small role="alert">โหลดประเภทเอกสารไม่สำเร็จ</small>}</label><label className="field">Date range<select className="select" aria-label="ช่วงเวลา" value={value.date_from||value.date_to?preset||"custom":""} onChange={e=>dates(e.target.value)}><option value="">All time</option><option value="7">7 วันที่ผ่านมา</option><option value="30">30 วันที่ผ่านมา</option><option value="90">90 วันที่ผ่านมา</option><option value="custom">กำหนดวันที่เอง</option></select></label><label className="comparison-toggle"><input type="checkbox" checked={!archived} onChange={e=>onArchived(!e.target.checked)}/>Active pipelines only</label><button className="button secondary" aria-expanded={open} aria-controls="comparison-secondary-filters" onClick={()=>setOpen(v=>!v)}><SlidersHorizontal size={16}/> Filters</button></div><div id="comparison-secondary-filters" className="comparison-secondary" hidden={!open&&!value.pipeline&&!value.date_from&&!value.date_to}><label className="field">Pipeline<select className="select" aria-label="Pipeline" value={value.pipeline??""} onChange={e=>onChange({...value,pipeline:e.target.value||undefined})}><option value="">ทุก Pipeline</option>{pipelines.map(p=><option key={p.pipeline_id} value={p.pipeline_id}>{p.pipeline_name}{p.retired?" · เก็บถาวร":""}</option>)}</select></label><label className="field">วันที่สร้างชุดทดสอบ · จากวันที่<input className="input" type="date" value={value.date_from??""} onChange={e=>{setPreset("custom");onChange({...value,date_from:e.target.value||undefined});}}/></label><label className="field">วันที่สร้างชุดทดสอบ · ถึงวันที่<input className="input" type="date" value={value.date_to??""} min={value.date_from} onChange={e=>{setPreset("custom");onChange({...value,date_to:e.target.value||undefined});}}/></label><label className="field">ค้นหาเอกสารในหน้านี้<input className="input" value={search} onChange={e=>onSearch(e.target.value)}/></label><button className="button secondary" onClick={onReset}>ล้างตัวกรอง</button><small>วันที่สร้างชุดทดสอบตาม UTC · การค้นหาชื่อมีผลเฉพาะตารางหน้าปัจจุบัน</small></div></>;
}
