"use client";
import type {Comparison,Identity,Pair} from "@/types/comparison";
import {percent} from "@/components/MatrixTable";
import {minimumCer,isMinimumCer,BestCerBadge} from "@/components/BestCer";
export {default as Scatter} from "@/components/AccuracySpeedChart";

export function nameOf(id:string|null,identities:Identity[]){return identities.find(p=>p.pipeline_id===id)?.pipeline_name||id||"—";}
export function verdict(p:Pair,identities:Identity[]){return p.verdict==="insufficient"?"ข้อมูลยังไม่พอ":p.verdict==="inconclusive"?"สูสี ยังสรุปไม่ได้":`${nameOf(p.winner,identities)} ดีกว่าชัดเจน`;}
function ByTypeTable({data}:{data:Comparison}){
 return <section className="panel panel-body"><h2 className="text-lg font-semibold">ควรใช้ Pipeline ไหนกับเอกสารประเภทนี้?</h2><div className="table-wrap" tabIndex={0}><table className="data-table" style={{minWidth:700}} aria-label="เปรียบเทียบตามประเภทเอกสาร"><thead><tr><th>ประเภทเอกสาร</th>{data.pipelines.map(p=><th key={p.pipeline_id}>{p.pipeline_name}{!p.active&&<span className="badge neutral">เก็บถาวร</span>}</th>)}</tr></thead><tbody>{data.by_type.filter(g=>g.code!=="unassigned").map(g=>{const best=minimumCer(g.decision.cells.map(c=>c.cer));return <tr key={g.code}><td style={{minWidth:260}}><strong>{g.name}</strong>{g.archived&&<span className="badge neutral">เก็บถาวร</span>}<p>{g.documents} เอกสารในขอบเขต</p><p className="font-semibold">{g.decision.recommendation?`แนะนำ: ${nameOf(g.decision.recommendation,data.pipelines)}`:g.decision.featured_pair&&g.decision.featured_pair.documents>=data.minimum_documents?"ยังไม่มีผู้ชนะชัดเจน":`ยังไม่พอจัดอันดับ · มี ${g.decision.featured_pair?.documents??0} จาก ${data.minimum_documents} เอกสารที่ต้องมี`}</p>{new Set(g.decision.cells.map(c=>c.documents)).size>1&&<p className="filter-note">จำนวนเอกสารที่ประเมินต่างกัน</p>}</td>{g.decision.cells.map(c=><td key={c.pipeline_id} className={isMinimumCer(c.cer,best.minimum)?"comparison-cer-best":c.cer===null?"comparison-cer-missing":undefined}><span title="Descriptive CER for this pipeline within this document type">Type overall CER {percent(c.cer)}</span>{isMinimumCer(c.cer,best.minimum)&&<BestCerBadge tied={best.tied} type/>}{g.decision.recommendation===c.pipeline_id&&<span className="badge info">แนะนำ</span>}<span className="row-meta">n={c.documents} เอกสาร</span></td>)}</tr>;})}</tbody></table></div><p className="filter-note">ตัวเลขในแต่ละช่องคำนวณจากเอกสารที่ Pipeline นั้นมีผล ส่วนคำแนะนำคำนวณจากเอกสารชุดเดียวกันแบบเทียบเป็นคู่</p></section>;
}

export function ByType({data}:{data:Comparison}){
 return <><div className="grid grid-cols-1 md:grid-cols-2 gap-4" aria-label="คำแนะนำตามประเภทเอกสาร">{data.by_type.filter(g=>g.code!=="unassigned").map(g=>{
 const d=g.decision,p=d.featured_pair,leader=d.ranking[0];
 return <section className="panel panel-body" key={g.code}><h2 className="text-lg font-semibold">{g.name}</h2>{g.archived&&<span className="badge neutral">เก็บถาวร</span>}<p className="font-semibold mt-2">{d.recommendation?`แนะนำตอนนี้: ${nameOf(d.recommendation,data.pipelines)}`:p&&p.documents>=data.minimum_documents?"ยังตัดสินผู้ชนะไม่ได้":"ข้อมูลยังไม่เพียงพอ"}</p>{!d.recommendation&&leader&&<p>{leader.pipeline_name} นำเชิงตัวเลข</p>}<p>เทียบตรงกัน {p?.documents??0} เอกสาร · {p?.test_cases??0} ชุดทดสอบ</p><p className="filter-note">ทั้งหมดในขอบเขต {g.documents} เอกสาร</p><p>ขั้นตอนต่อไป: {d.readiness.reasons.missing_gt?`ยืนยัน GT อีก ${d.readiness.reasons.missing_gt} ชุด`:d.readiness.reasons.not_run?`รันคู่หลักอีก ${d.readiness.reasons.not_run} ชุด`:d.readiness.reasons.failed?`ตรวจผลรันไม่สำเร็จ ${d.readiness.reasons.failed} ชุด`:p&&p.documents<data.minimum_documents?`เพิ่มเอกสารที่เทียบตรงกันอีก ${data.minimum_documents-p.documents} เอกสาร`:"ตรวจผลรายชุดและเพิ่มเอกสารที่ยืนยัน"}</p></section>;
 })}</div><details className="panel panel-body"><summary className="cursor-pointer font-semibold">ดูตารางทุก Pipeline</summary><ByTypeTable data={data}/></details></>;
}
