"use client";
import Link from "next/link";
import type {Comparison,Decision,Identity,Pair} from "@/types/comparison";
import {percent} from "@/components/MatrixTable";

const number=(n:number|null|undefined)=>n==null?"—":n.toLocaleString("th-TH",{maximumFractionDigits:2});
export function nameOf(id:string|null,identities:Identity[]){return identities.find(p=>p.pipeline_id===id)?.pipeline_name||id||"—";}
export function verdict(p:Pair,identities:Identity[]){return p.verdict==="insufficient"?"ข้อมูลยังไม่พอ":p.verdict==="inconclusive"?"สูสี ยังสรุปไม่ได้":`${nameOf(p.winner,identities)} ดีกว่าชัดเจน`;}
export function PairDetail({decision,identities}:{decision:Decision;identities:Identity[]}){
 return <details className="panel panel-body"><summary className="cursor-pointer font-semibold">รายละเอียดการเทียบเป็นคู่</summary><p className="filter-note">เทียบเฉพาะชุดที่ทั้งคู่มี GT ยืนยันและผลประเมินสุดท้าย · PDF หลายหน้านับเป็นเอกสารเดียว · ช่วง 95% จากการสุ่มเอกสารซ้ำ 2,000 ครั้ง ไม่ใช่การรับรองว่าชนะเสมอ</p>
 <PairTable pairs={decision.pairs} identities={identities}/>
 {decision.historical_pairs.length>0&&<><h3>ข้อมูลคู่ในอดีต (เก็บถาวร) — ไม่ใช้แนะนำตอนนี้</h3><PairTable pairs={decision.historical_pairs} identities={identities}/></>}
 </details>;
}
function PairTable({pairs,identities}:{pairs:Pair[];identities:Identity[]}){
 return <div className="table-wrap" tabIndex={0}><table className="data-table" aria-label="หลักฐานการเทียบคู่"><thead><tr>{["คู่ Pipeline","เอกสาร / ชุด","CER A / B","ส่วนต่าง A − B (pp)","ช่วง 95% (pp)","A ชนะ / เสมอ / B ชนะ","ข้อสรุป"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{pairs.map(p=><tr key={`${p.a}:${p.b}`}><td>{nameOf(p.a,identities)} ↔ {nameOf(p.b,identities)}{(!identities.find(i=>i.pipeline_id===p.a)?.active||!identities.find(i=>i.pipeline_id===p.b)?.active)&&<span className="badge neutral">เก็บถาวร</span>}</td><td>{p.documents} / {p.test_cases}</td><td>{percent(p.mean_cer_a)} / {percent(p.mean_cer_b)}</td><td>{number(p.mean_dcer_pp)}</td><td>{p.ci95_pp?p.ci95_pp.map(number).join(" ถึง "):"—"}</td><td>{p.wins} / {p.ties} / {p.losses}</td><td>{verdict(p,identities)}</td></tr>)}</tbody></table>{!pairs.length&&<p className="filter-note">ต้องมี Pipeline ที่ใช้งานอยู่อย่างน้อยสองตัวเพื่อเทียบเป็นคู่</p>}</div>;
}
export function DecisionOverview({data}:{data:Comparison}){
 const d=data.overall,r=d.readiness,p=d.featured_pair;
 const leader=d.ranking[0], recommended=d.recommendation;
 const leaderCer=p?(p.a===leader?.pipeline_id?p.mean_cer_a:p.mean_cer_b):null;
 return <>
 <section className="panel panel-body" aria-label="ความพร้อมคู่หลัก"><h2 className="text-lg font-semibold">{r.valid_pair?`ข้อมูลพร้อมเทียบคู่หลัก ${r.x} / ${r.y} ชุด`:"ยังไม่มีคู่ที่เทียบได้"}</h2>
 {p?<><p>{nameOf(p.a,data.pipelines)} ↔ {nameOf(p.b,data.pipelines)}</p><p>{r.x} ชุดทดสอบ จาก {r.documents} เอกสาร · มี GT และผลที่ใช้เทียบได้จากทั้งสอง Pipeline</p><p className="filter-note">Ground Truth (GT) คือข้อความถูกต้องที่ผู้ใช้ยืนยัน · ที่เหลือ {r.y-r.x} ชุด: ยังไม่มี GT ยืนยัน {r.reasons.missing_gt} · ยังไม่ได้รันคู่หลัก {r.reasons.not_run} · รันไม่สำเร็จ {r.reasons.failed} · ไม่เข้าเกณฑ์อื่น {r.reasons.other}</p></>:<p>{r.reason}</p>}</section>
 <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
 <section className="panel panel-body" aria-label="คำแนะนำปัจจุบัน"><h2 className="text-xl font-semibold">{recommended?"แนะนำตอนนี้":"ยังไม่มี Pipeline ที่ชนะชัดเจน"}</h2><p className="mt-3 font-semibold">{recommended?nameOf(recommended,data.pipelines):leader?`ผู้นำเชิงตัวเลข: ${leader.pipeline_name}`:"ยังไม่มี Pipeline ที่ใช้งานอยู่ในขอบเขตนี้"}</p>{p&&<p>CER เฉลี่ย {percent(leaderCer)} · {p.documents} เอกสาร / {p.test_cases} ชุด · ยิ่งต่ำยิ่งดี</p>}{!recommended&&<p className="filter-note">ยังสรุปไม่ได้จากหลักฐานปัจจุบัน ต้องมีคะแนนนำเพียงตัวเดียว ไม่แพ้ชัดเจนให้คู่ใด และชนะอันดับสองชัดเจน</p>}<p className="mt-2 font-semibold">ขั้นต่อไป: {r.reasons.missing_gt>0?`ยืนยัน GT เพิ่ม ${r.reasons.missing_gt} ชุด`:r.reasons.not_run>0?`รันคู่หลักให้ครบอีก ${r.reasons.not_run} ชุด`:r.reasons.failed>0?`ตรวจผลรันไม่สำเร็จ ${r.reasons.failed} ชุด`:"ดูหลักฐานคู่และเพิ่มเอกสารที่ทั้งคู่มีผลยืนยัน"}</p><a className="button secondary mt-3" href="#comparison-pairs">ดูรายละเอียดการเทียบ</a></section>
 <section className="panel panel-body" aria-label="ผลเทียบคู่หลัก"><h2 className="text-lg font-semibold">เทียบกันตรง ๆ บนเอกสารชุดเดียวกัน</h2>{p?<><p className="mt-3">{nameOf(p.a,data.pipelines)} ดีกว่า {p.wins} เอกสาร · เสมอ {p.ties} · {nameOf(p.b,data.pipelines)} ดีกว่า {p.losses}</p><p>ส่วนต่าง CER (A − B) {number(p.mean_dcer_pp)} pp · ค่าติดลบหมายถึง A ดีกว่า</p><p>ช่วง 95%: {p.ci95_pp?p.ci95_pp.map(number).join(" ถึง ")+" pp":"ข้อมูลไม่พอคำนวณ"}</p><p>{p.documents} เอกสาร · {p.test_cases} ชุด · <strong>{verdict(p,data.pipelines)}</strong></p><p className="filter-note">ช่วงนี้สะท้อนความไม่แน่นอนของข้อมูลชุดนี้ หากคร่อม 0 ยังสรุปผู้ชนะไม่ได้ · ต้องมีอย่างน้อย {data.minimum_documents} เอกสาร</p></>:<p>เลือกอย่างน้อยสอง Pipeline ที่ใช้งานอยู่</p>}</section>
 </div>
 <Scatter decision={d}/>
 <section className="panel panel-body"><h2 className="text-lg font-semibold">สิ่งที่ควรทำต่อ</h2><ul className="list-disc pl-5 mt-3 space-y-2">
 {data.actions.missing_gt>0&&<li>ใส่ GT และยืนยันเพิ่ม {data.actions.missing_gt} ชุดที่ยังไม่มีข้อความถูกต้องยืนยัน</li>}
 {data.actions.missing_runs.filter(a=>a.count>0).map(a=><li key={a.pipeline_id}>รัน {a.pipeline_name} เพิ่มใน {a.count} ชุดที่ Pipeline อื่นเคยรันแล้ว</li>)}
 {data.actions.failed_runs.filter(a=>a.count>0).map(a=><li key={a.pipeline_id}>ตรวจผลรันไม่สำเร็จของ {a.pipeline_name}: {a.count} ชุด</li>)}
 {data.actions.short_types.map(t=><li key={t.code}>{t.name}: มีผลประเมินจาก {t.documents} เอกสาร ต้องเพิ่มอย่างน้อย {t.needed} เอกสารให้ถึง {data.minimum_documents} (คู่เปรียบเทียบยังต้องมีผลครบทั้งคู่)</li>)}
 </ul><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">{[["ชุดที่ผลต่างกันมาก",data.actions.largest_spread],["ชุดที่แม้ผลดีที่สุดยังมี CER สูง",data.actions.hardest]].map(([title,items])=><div key={String(title)}><h3 className="font-semibold">{String(title)}</h3><ul>{(items as typeof data.actions.hardest).map(c=><li key={c.test_case_id}><Link className="text-link" href={c.href}>{c.filename}</Link> · {title==="ชุดที่ผลต่างกันมาก"?`ส่วนต่าง ${percent(c.spread)}`:`CER ดีที่สุด ${percent(c.best_cer)}`}</li>)}</ul></div>)}</div></section>
 <div id="comparison-pairs"><PairDetail decision={d} identities={data.pipelines}/></div>
 </>;
}
function Scatter({decision}:{decision:Decision}){
 const s=decision.scatter, points=s.points.filter(p=>p.cer!==null&&p.time_seconds!==null);
 const maxX=Math.max(1,...points.map(p=>p.time_seconds!))*1.15,maxY=Math.max(.01,...points.map(p=>p.cer!))*1.15;
 const x=(n:number)=>70+n/maxX*580,y=(n:number)=>285-n/maxY*220;
 const frontier=points.filter(p=>p.active&&p.pareto).sort((a,b)=>a.time_seconds!-b.time_seconds!);
 return <section className="panel panel-body"><h2 className="text-lg font-semibold">ความแม่นยำ × เวลา</h2><p className="filter-note">CER และเวลายิ่งต่ำยิ่งดี · มุมซ้ายล่างดีกว่า · จุดทึบต้องมี ≥5 เอกสารที่ประเมินและ ≥5 ผลรันที่มีเวลา</p>{!s.pareto_valid&&<p className="notice-banner">{s.cohort_mode==="own"?"ชุดเอกสารไม่ตรงกัน เทียบกันตรง ๆ ไม่ได้":"เวลาของบาง Pipeline ไม่ครบ จึงยังไม่แสดงแนว Pareto"}</p>}
 <svg role="img" aria-label="กราฟ CER เฉลี่ยกับเวลาเฉลี่ยต่อชุดทดสอบ" viewBox="0 0 720 350" className="w-full"><line x1="70" y1="285" x2="650" y2="285" stroke="currentColor"/><line x1="70" y1="65" x2="70" y2="285" stroke="currentColor"/>{[0,.5,1].map(t=><g key={t}><text x={x(maxX*t)} y="307" textAnchor="middle" fontSize="12">{number(maxX*t)}</text><text x="60" y={y(maxY*t)} textAnchor="end" fontSize="12">{percent(maxY*t)}</text></g>)}<text x="350" y="338" textAnchor="middle" fontSize="14">เวลาเฉลี่ยต่อชุดทดสอบ (วินาที)</text><text x="70" y="35" fontSize="14">CER เฉลี่ย</text>
 {s.pareto_valid&&frontier.length>0&&<polyline data-testid="pareto-frontier" points={frontier.map(p=>`${x(p.time_seconds!)},${y(p.cer!)}`).join(" ")} fill="none" stroke="#0d9488" strokeWidth="2"/>}
 {points.map((p,i)=><circle key={p.pipeline_id} cx={x(p.time_seconds!)} cy={y(p.cer!)} r="7" tabIndex={0} aria-label={`${p.pipeline_name}: CER ${percent(p.cer)}, ${number(p.time_seconds)} วินาที, ${p.documents} เอกสาร, ${p.timed_runs} runs, ${p.cohort_mode}, ${p.active?"ใช้งานอยู่":"เก็บถาวร"}`} fill={p.filled?`hsl(${i*65},60%,40%)`:"white"} stroke={`hsl(${i*65},60%,40%)`} strokeWidth="2" strokeDasharray={!p.active?"3 2":undefined}><title>{p.pipeline_name} · CER {percent(p.cer)} · {number(p.time_seconds)} วินาที · n={p.documents} เอกสาร · {p.timed_runs} runs · {p.cohort_mode} · {p.active?"ใช้งานอยู่":"เก็บถาวร"}</title></circle>)}</svg>
 <ul className="filter-note">{s.points.map(p=><li key={p.pipeline_id}>{p.pipeline_name}{!p.active?" · เก็บถาวร":""} · CER {percent(p.cer)} · {number(p.time_seconds)} วินาที · n={p.documents} เอกสาร / {p.timed_runs} runs · {p.cohort_mode==="common"?"เอกสารร่วมกัน":"เอกสารของ Pipeline นี้"}{p.pareto&&s.pareto_valid?" · แนว Pareto":""}</li>)}</ul><p className="filter-note">เอกสารร่วมกันของ active ทั้งหมด: {s.common_documents} เอกสาร / {s.common_test_cases} ชุด · เวลาของ Global workflow เป็นผลรวมเวลา Field ไม่ใช่เวลารอทั้งหน้า</p></section>;
}
export function ByType({data}:{data:Comparison}){
 return <section className="panel panel-body"><h2 className="text-lg font-semibold">ควรใช้ Pipeline ไหนกับเอกสารประเภทนี้?</h2><div className="table-wrap" tabIndex={0}><table className="data-table" style={{minWidth:700}} aria-label="เปรียบเทียบตามประเภทเอกสาร"><thead><tr><th>ประเภทเอกสาร</th>{data.pipelines.map(p=><th key={p.pipeline_id}>{p.pipeline_name}{!p.active&&<span className="badge neutral">เก็บถาวร</span>}</th>)}</tr></thead><tbody>{data.by_type.map(g=><tr key={g.code}><td style={{minWidth:260}}><strong>{g.name}</strong>{g.archived&&<span className="badge neutral">เก็บถาวร</span>}<p>{g.documents} เอกสารในขอบเขต</p><p className="font-semibold">{g.decision.recommendation?`แนะนำ: ${nameOf(g.decision.recommendation,data.pipelines)}`:g.decision.featured_pair&&g.decision.featured_pair.documents>=data.minimum_documents?"ยังไม่มีผู้ชนะชัดเจน":`ยังไม่พอจัดอันดับ · มี ${g.decision.featured_pair?.documents??0} จาก ${data.minimum_documents} เอกสารที่ต้องมี`}</p>{new Set(g.decision.cells.map(c=>c.documents)).size>1&&<p className="filter-note">n ต่างกัน — ดูเทียบทีละคู่</p>}<PairDetail decision={g.decision} identities={data.pipelines}/></td>{g.decision.cells.map(c=><td key={c.pipeline_id} style={{backgroundColor:c.cer===null?undefined:`rgba(13,148,136,${Math.min(.2,c.cer*.2)})`}}>{percent(c.cer)}<span className="row-meta">n={c.documents} เอกสาร</span></td>)}</tr>)}</tbody></table></div><p className="filter-note">ตัวเลขในแต่ละช่องคำนวณจากเอกสารที่ Pipeline นั้นมีผล ส่วนคำแนะนำคำนวณจากเอกสารชุดเดียวกันแบบเทียบเป็นคู่</p></section>;
}
