import type {EvaluationMode,GlobalField} from "@/types";
import {completeGT,joinFieldGT,orderedGTFields} from "@/lib/ground-truth-sync";

type Props={mode:EvaluationMode;fields:GlobalField[];documentGT:string;lineCounts:number[];busy:boolean;onMode:(m:EvaluationMode)=>void;onLineCounts:(counts:number[])=>void;onDocument:(text:string)=>void;onField:(f:GlobalField)=>void;onSave:(calculate:boolean)=>void;onActivateField?:(id:string)=>void};
const name=(f:GlobalField)=>`Field ${String(f.field_index).padStart(2,"0")}`;

export default function GlobalGroundTruthForm({mode,fields,documentGT,lineCounts,busy,onMode,onLineCounts,onDocument,onField,onSave,onActivateField}:Props){
 const ordered=orderedGTFields(fields),whole=mode==="whole_document",ready=completeGT(fields,documentGT);
 const missing=ordered.filter(f=>!f.ground_truth_raw?.trim());
 const conflict=!!documentGT.trim()&&fields.some(f=>f.ground_truth_raw?.trim())&&joinFieldGT(fields)!==documentGT;
 const card="block rounded-xl border border-slate-300 bg-slate-50 p-4 space-y-3 focus-within:border-sky-600 focus-within:ring-2 focus-within:ring-sky-600/25";
 const input="textarea w-full rounded-lg border border-slate-300 bg-white p-3 focus:border-sky-600 focus:outline-none focus:ring-2 focus:ring-sky-600/30";
 return <section className="panel panel-body space-y-5">
  <div className="flex gap-2" aria-label="Evaluation mode">{(["whole_document","per_field"] as const).map(m=><button key={m} disabled={busy} aria-pressed={m===mode} className={`button ${mode===m?"primary":"secondary"}`} onClick={()=>onMode(m)}>{m==="whole_document"?"Whole Field":"Sub-fields"}</button>)}</div>
  <p className="text-sm text-slate-600">กรอกในโหมดใดก็ได้ ข้อความจะซิงก์กันตามลำดับกรอบ ROI ต้องกรอกครบทั้ง {fields.length} Fields ก่อนยืนยันคำนวณ</p>
  {conflict&&<div className="rounded-lg border border-amber-300 bg-amber-50 p-3 space-y-2" role="alert"><p>GT เดิมสองโหมดไม่ตรงกัน เลือกข้อความที่จะใช้ซิงก์ก่อนคำนวณ</p><div className="flex flex-wrap gap-2"><button disabled={busy} className="button secondary" onClick={()=>onDocument(documentGT)}>ใช้ข้อความ Whole Field</button><button disabled={busy} className="button secondary" onClick={()=>onField(ordered[0])}>ใช้ข้อความ Sub-fields</button></div></div>}
  {whole?<>
   <label className={card} data-testid="whole-gt-card">Ground Truth ทั้งเอกสาร<textarea className={input} rows={10} aria-label="Ground Truth ทั้งเอกสาร" placeholder={ordered.map(f=>`${name(f)}: ข้อความในกรอบนี้`).join("\n")} disabled={busy} value={documentGT} onChange={e=>onDocument(e.target.value)}/></label>
   <div className="space-y-3 rounded-lg border border-slate-200 p-4" aria-label="แบ่งบรรทัดตาม ROI">
    <p className="text-sm font-semibold">ค่าเริ่มต้น: 1 บรรทัดต่อ Field</p>
    <p className="text-xs text-slate-500">เลือกเฉพาะ Field ที่ต้องการหลายบรรทัด แล้วระบุจำนวนบรรทัดรวม ส่วน Field สุดท้ายรับบรรทัดที่เหลือทั้งหมดอัตโนมัติ เพื่อไม่ให้ข้อความตกหล่น</p>
    {ordered.length>1&&<label className="block space-y-2 text-sm"><span>เพิ่ม Field ที่มีหลายบรรทัด</span><select className="w-full rounded-lg border border-slate-300 bg-white p-2" aria-label="เพิ่ม Field ที่มีหลายบรรทัด" value="" disabled={busy||ordered.slice(0,-1).every((_,i)=>(lineCounts[i]??1)>1)} onChange={e=>{const i=ordered.findIndex(f=>f.id===e.target.value);if(i>=0)onLineCounts(ordered.map((_,j)=>j===i?2:lineCounts[j]??1));}}><option value="">เลือก Field ที่ต้องการปรับ</option>{ordered.slice(0,-1).map((f,i)=>(lineCounts[i]??1)<=1&&<option key={f.id} value={f.id}>{name(f)}</option>)}</select></label>}
    {ordered.slice(0,-1).map((f,i)=>(lineCounts[i]??1)>1&&<div key={f.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-sky-50 p-3 text-sm"><label className="flex items-center gap-2"><span>{name(f)}</span><input type="number" min={2} max={10000} className="w-20 rounded border border-slate-300 bg-white p-2" aria-label={`จำนวนบรรทัด ${name(f)}`} value={lineCounts[i]} disabled={busy} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=2&&n<=10000)onLineCounts(ordered.map((_,j)=>j===i?n:lineCounts[j]??1));}}/><span>บรรทัดรวม</span></label><button type="button" className="text-sky-800 underline" disabled={busy} aria-label={`คืนค่า ${name(f)} เป็น 1 บรรทัด`} onClick={()=>onLineCounts(ordered.map((_,j)=>j===i?1:lineCounts[j]??1))}>คืนค่าเริ่มต้น</button></div>)}
   </div>
   {!!documentGT.trim()&&!fields.some(f=>f.ground_truth_raw?.trim())&&<button className="button secondary" disabled={busy} onClick={()=>onDocument(documentGT)}>แบ่งข้อความเดิมเข้า Sub-fields</button>}
  </>:<div className="max-h-[65vh] space-y-3 overflow-y-auto p-1">{ordered.map(f=><label key={f.id} className={card} data-testid="field-gt-input"><span>{name(f)}</span><span className="block text-xs text-slate-500">ROI ({f.roi.x1}, {f.roi.y1}) – ({f.roi.x2}, {f.roi.y2}) · รองรับหลายบรรทัด</span><textarea className={input} rows={3} aria-label={`Ground Truth ${name(f)}`} placeholder={`ข้อความทั้งหมดภายใน ${name(f)}`} disabled={busy} onFocus={()=>onActivateField?.(f.id)} onClick={()=>onActivateField?.(f.id)} value={f.ground_truth_raw??""} onChange={e=>onField({...f,ground_truth_raw:e.target.value})}/></label>)}</div>}
  <section className="space-y-2" aria-label="พรีวิวข้อความตาม Field"><h3 className="text-sm font-semibold">พรีวิวข้อความ → Field</h3><div className="max-h-64 overflow-auto rounded-lg border border-slate-200">{ordered.map(f=><div key={f.id} className="flex items-start gap-3 border-b border-slate-100 p-3 text-sm last:border-b-0" data-testid="gt-field-preview"><span className="min-w-0 flex-1 whitespace-pre-wrap break-words">{f.ground_truth_raw||<span className="text-slate-400">(ยังไม่มีข้อความ)</span>}</span><button type="button" disabled={busy} onClick={()=>onActivateField?.(f.id)} className="shrink-0 text-sky-800 underline" aria-label={`ดูกรอบ ${name(f)}`}>{name(f)}</button></div>)}</div><p className="text-xs text-slate-500">หนึ่งแถวต่อ Field โดยคงบรรทัดข้อความภายใน กดชื่อ Field เพื่อดูกรอบบนภาพ</p></section>
  <p role="status" data-testid="gt-completeness" className={ready?"text-sm text-emerald-700":"text-sm text-amber-800"}>{ready?`กรอกครบ ${fields.length}/${fields.length} Fields แล้ว`:missing.length?`ยังไม่ครบ: ${missing.map(name).join(", ")}`:"กรุณาซิงก์ข้อความสองโหมดให้ตรงกันก่อนคำนวณ"}</p>
  <p data-testid="calculation-hint" className="text-xs text-slate-500">บันทึกฉบับร่างได้แม้ยังกรอกไม่ครบ การยืนยันจะบันทึก GT และคำนวณคะแนนทั้ง Whole Field และ Sub-fields จากผล OCR ที่บันทึกไว้ ไม่เรียกโมเดล OCR ซ้ำ</p>
  <div className="flex flex-wrap gap-2"><button className="button secondary" disabled={busy} onClick={()=>onSave(false)}>บันทึก GT ฉบับร่าง</button><button className="button primary" disabled={busy||!ready} onClick={()=>onSave(true)}>ยืนยันเพื่อคำนวณ</button></div>
 </section>;
}
